# Dependency Security Review - GitHub Composite Action
#
# Performs a security audit of changed or updated dependencies in a pull request
# using Claude Code. Detects dependency changes automatically or accepts a
# specific dependency to review via the `dependency` input.

name: "Dependency Security Review"
description: "Security audit of changed or updated dependencies using Claude Code"

inputs:
  anthropic_api_key:
    description: "Anthropic API key for Claude Code (required unless oauth_token is set)"
    required: false
    default: ""
  oauth_token:
    description: "Claude Code OAuth token for subscription-based auth (Pro/Max/Teams/Enterprise). Generate with 'claude setup-token'."
    required: false
    default: ""
  dependency:
    description: "Force review of specific dependencies. Comma-separated for multiple (e.g., github.com/lib/pq 1.10.0..1.11.0,serde 1.0.196..1.0.197). Bypasses auto-detection."
    required: false
    default: ""
  ecosystem:
    description: "Override ecosystem detection (go or rust). Useful with force-review dependency input when auto-detection may fail."
    required: false
    default: ""
  model:
    description: "Claude model to use"
    required: false
    default: "sonnet"
  max_turns:
    description: "Maximum agentic conversation turns"
    required: false
    default: "50"

outputs:
  review:
    description: "Full markdown review text"
    value: ${{ steps.review.outputs.review }}
  dependencies:
    description: "Dependencies that were reviewed"
    value: ${{ steps.detect.outputs.dependencies }}
  ecosystem:
    description: "Detected ecosystem(s)"
    value: ${{ steps.detect.outputs.ecosystem }}
  input_tokens:
    description: "Number of input tokens used"
    value: ${{ steps.review.outputs.input_tokens }}
  output_tokens:
    description: "Number of output tokens used"
    value: ${{ steps.review.outputs.output_tokens }}
  total_tokens:
    description: "Total number of tokens used"
    value: ${{ steps.review.outputs.total_tokens }}
  report_dir:
    description: "Path to the directory containing the review report files"
    value: ${{ steps.review.outputs.report_dir }}

runs:
  using: "composite"
  steps:
    # Step 0: Install Python dependencies (GitPython, PyGithub, etc.).
    - name: Install Python dependencies
      run: pip install -q -r ${{ github.action_path }}/requirements.txt
      shell: bash

    # Step 1: Detect which dependencies have changed in the pull request.
    # If the `dependency` input is provided, auto-detection is bypassed.
    - name: Detect dependency changes
      id: detect
      run: python3 ${{ github.action_path }}/scripts/detect_changes.py
      shell: bash
      env:
        INPUT_DEPENDENCY: ${{ inputs.dependency }}
        INPUT_ECOSYSTEM: ${{ inputs.ecosystem }}
        ACTION_PATH: ${{ github.action_path }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}

    # Step 1.5: Install ecosystem-specific dependency scanning tools.
    # These are used by Claude during the review to scan for known
    # vulnerabilities before supplementing with online database research.
    - name: Install dependency scanning tools
      id: scan-tools
      if: steps.detect.outputs.has_changes == 'true'
      run: |
        ECOSYSTEM="${{ steps.detect.outputs.ecosystem }}"
        # Validate ecosystem value to prevent injection
        case "$ECOSYSTEM" in
          go|rust|mixed|none|unknown) ;;
          *) echo "::error::Invalid ecosystem value: '$ECOSYSTEM'"; exit 1 ;;
        esac
        TOOLS=""
        if [ "$ECOSYSTEM" = "go" ] || [ "$ECOSYSTEM" = "mixed" ]; then
          if command -v go &>/dev/null; then
            echo "Installing govulncheck..."
            go install golang.org/x/vuln/cmd/govulncheck@latest
            TOOLS="${TOOLS:+$TOOLS,}govulncheck"
          else
            echo "::warning::Go toolchain not found — skipping govulncheck"
          fi
        fi
        if [ "$ECOSYSTEM" = "rust" ] || [ "$ECOSYSTEM" = "mixed" ]; then
          if command -v cargo &>/dev/null; then
            echo "Installing cargo-audit..."
            cargo install cargo-audit
            TOOLS="${TOOLS:+$TOOLS,}cargo-audit"
          else
            echo "::warning::Rust toolchain not found — skipping cargo-audit"
          fi
        fi
        echo "tools=$TOOLS" >> "$GITHUB_OUTPUT"
      shell: bash

    # Step 2: Prepare the Claude Code environment (copy agent configs).
    - name: Setup Claude environment
      id: setup
      if: steps.detect.outputs.has_changes == 'true'
      run: python3 ${{ github.action_path }}/scripts/setup_claude.py
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}

    # Step 3: Build the review prompt from detected changes and ecosystem context.
    - name: Generate review prompt
      id: prompt
      if: steps.detect.outputs.has_changes == 'true'
      run: python3 ${{ github.action_path }}/scripts/generate_prompt.py
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        ECOSYSTEM: ${{ steps.detect.outputs.ecosystem }}
        DEPENDENCIES: ${{ steps.detect.outputs.dependencies }}
        INPUT_DEPENDENCY: ${{ inputs.dependency }}

    # Step 4: Install the Claude Code CLI (required by claude-agent-sdk).
    - name: Install Claude Code CLI
      if: steps.detect.outputs.has_changes == 'true'
      run: npm install -g @anthropic-ai/claude-code
      shell: bash

    # Step 5: Execute the Claude Code security review via the Python SDK.
    #
    # Only set each auth env-var when the corresponding input is non-empty.
    # An empty CLAUDE_CODE_OAUTH_TOKEN that still *exists* in the
    # environment can cause the CLI to attempt OAuth auth (and fail)
    # instead of using the valid ANTHROPIC_API_KEY.
    - name: Run Claude Code review
      id: review
      if: steps.detect.outputs.has_changes == 'true'
      run: |
        [ -z "$_OAUTH" ] && unset CLAUDE_CODE_OAUTH_TOKEN
        [ -z "$_APIKEY" ] && unset ANTHROPIC_API_KEY
        # Strip sensitive GitHub tokens to prevent leakage to Claude
        unset GITHUB_TOKEN GH_TOKEN ACTIONS_RUNTIME_TOKEN ACTIONS_ID_TOKEN_REQUEST_TOKEN
        python3 ${{ github.action_path }}/scripts/run_claude.py
      shell: bash
      env:
        _APIKEY: ${{ inputs.anthropic_api_key }}
        _OAUTH: ${{ inputs.oauth_token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        CLAUDE_CODE_OAUTH_TOKEN: ${{ inputs.oauth_token }}
        CLAUDE_MODEL: ${{ inputs.model }}
        MAX_TURNS: ${{ inputs.max_turns }}
        PROMPT_FILE: ${{ steps.prompt.outputs.prompt_file }}
        ECOSYSTEM: ${{ steps.detect.outputs.ecosystem }}
        SCANNING_TOOLS: ${{ steps.scan-tools.outputs.tools }}

    # Step 6: Post the review results as a comment on the pull request.
    # Run even if the review step failed so error details appear on the PR.
    - name: Post PR comment
      id: comment
      if: steps.detect.outputs.has_changes == 'true' && !cancelled()
      run: python3 ${{ github.action_path }}/scripts/post_comment.py
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REVIEW_FILE: ${{ steps.review.outputs.review_file }}
        ECOSYSTEM: ${{ steps.detect.outputs.ecosystem }}
        DEPENDENCIES: ${{ steps.detect.outputs.dependencies }}
        INPUT_TOKENS: ${{ steps.review.outputs.input_tokens }}
        OUTPUT_TOKENS: ${{ steps.review.outputs.output_tokens }}
        TOTAL_TOKENS: ${{ steps.review.outputs.total_tokens }}
        TOTAL_COST_USD: ${{ steps.review.outputs.total_cost_usd }}
        NUM_TURNS: ${{ steps.review.outputs.num_turns }}

    # Step 7: Upload the review report as a GitHub Actions artifact.
    - name: Upload review report artifact
      if: steps.detect.outputs.has_changes == 'true' && !cancelled()
      uses: actions/upload-artifact@v4
      with:
        name: dependency-security-review
        path: ${{ steps.review.outputs.report_dir }}
        if-no-files-found: warn
        retention-days: 90
