#!/usr/bin/env python3
"""
post_comment.py

Posts or updates a sticky PR comment with the dependency security review.
Uses PyGithub for all GitHub API interactions.
Falls back to GITHUB_STEP_SUMMARY when no PR context is available.
"""

import os
import sys

from github import Auth, Github

_MARKER_PREFIX = "<!-- yeah-action-dependency-review"
_MARKER_SUFFIX = " -->"


def main():
    for var in ("GH_TOKEN", "REVIEW_FILE"):
        if not os.environ.get(var):
            print(f"Error: {var} must be set", file=sys.stderr)
            sys.exit(1)

    token = os.environ["GH_TOKEN"]
    review_file = os.environ["REVIEW_FILE"]
    ecosystem = os.environ.get("ECOSYSTEM", "unknown")
    dependencies = os.environ.get("DEPENDENCIES", "none")
    github_repo = os.environ.get("GITHUB_REPOSITORY", "")
    step_summary = os.environ.get("GITHUB_STEP_SUMMARY", os.devnull)
    action_repo = os.environ.get("GITHUB_ACTION_REPOSITORY",
                                 "lklimek/yeah-action")
    pr_number = os.environ.get("PR_NUMBER", "0") or "0"

    if not github_repo:
        print("Error: GITHUB_REPOSITORY must be set", file=sys.stderr)
        sys.exit(1)

    if not os.path.isfile(review_file):
        print(f"Error: Review file not found at {review_file}",
              file=sys.stderr)
        sys.exit(1)

    with open(review_file) as f:
        review_content = f.read()

    marker = f"{_MARKER_PREFIX}: {dependencies}{_MARKER_SUFFIX}"

    comment_body = (
        f"{marker}\n"
        f"## Dependency Security Review\n\n"
        f"| Field | Value |\n"
        f"|-------|-------|\n"
        f"| **Ecosystem** | {ecosystem} |\n"
        f"| **Dependencies** | {dependencies} |\n\n"
        f"---\n\n"
        f"{review_content}\n\n"
        f"---\n"
        f"<sub>Generated by [yeah-action](https://github.com/{action_repo}) "
        f"dependency security review</sub>"
    )

    max_length = 65000
    if len(comment_body) > max_length:
        print(f"Warning: Comment body exceeds {max_length} characters; "
              "truncating.")
        comment_body = comment_body[:max_length] + "\n\n... (truncated)"

    if pr_number == "0":
        print("No pull request context detected. Writing to step summary.")
        with open(step_summary, "a") as f:
            f.write(comment_body)
            f.write("\n")
        print("Review written to GITHUB_STEP_SUMMARY.")
        return

    g = Github(auth=Auth.Token(token))
    repo = g.get_repo(github_repo)
    pr = repo.get_pull(int(pr_number))

    print(f"Searching for existing review comment on PR #{pr_number}...")
    existing_comment = None
    for comment in pr.get_issue_comments():
        if marker in comment.body:
            existing_comment = comment
            break

    if existing_comment:
        print(f"Updating existing comment (ID: {existing_comment.id})...")
        existing_comment.edit(comment_body)
        print("Comment updated.")
    else:
        print(f"Creating new comment on PR #{pr_number}...")
        pr.create_issue_comment(comment_body)
        print("Comment created.")

    g.close()
    print("PR comment posted successfully.")


if __name__ == "__main__":
    main()
