#!/usr/bin/env bash
set -euo pipefail

# Posts or updates a sticky PR comment with the dependency security review.
# Falls back to GITHUB_STEP_SUMMARY when no PR context is available.

: "${GH_TOKEN:?GH_TOKEN must be set}"
: "${REVIEW_FILE:?REVIEW_FILE must be set}"

ECOSYSTEM="${ECOSYSTEM:-unknown}"
DEPENDENCIES="${DEPENDENCIES:-none}"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:?GITHUB_REPOSITORY must be set}"
GITHUB_STEP_SUMMARY="${GITHUB_STEP_SUMMARY:-/dev/null}"

# ---------------------------------------------------------------
# Read review content
# ---------------------------------------------------------------
if [[ ! -f "${REVIEW_FILE}" ]]; then
  echo "Error: Review file not found at ${REVIEW_FILE}" >&2
  exit 1
fi

REVIEW_CONTENT=$(cat "${REVIEW_FILE}")

# ---------------------------------------------------------------
# Build the comment body
# ---------------------------------------------------------------
MARKER="<!-- yeah-action-dependency-review -->"

COMMENT_BODY="${MARKER}
## Dependency Security Review

| Field | Value |
|-------|-------|
| **Ecosystem** | ${ECOSYSTEM} |
| **Dependencies** | ${DEPENDENCIES} |

---

${REVIEW_CONTENT}

---
<sub>Generated by [yeah-action](https://github.com/${GITHUB_ACTION_REPOSITORY:-lklimek/yeah-action}) dependency security review</sub>"

# ---------------------------------------------------------------
# Truncate if needed (GitHub limit: 65535 chars)
# ---------------------------------------------------------------
MAX_LENGTH=65000
if [[ ${#COMMENT_BODY} -gt ${MAX_LENGTH} ]]; then
  echo "Warning: Comment body exceeds ${MAX_LENGTH} characters; truncating."
  COMMENT_BODY="${COMMENT_BODY:0:${MAX_LENGTH}}

... (truncated)"
fi

# ---------------------------------------------------------------
# If there is no PR, write to step summary instead
# ---------------------------------------------------------------
PR_NUMBER="${PR_NUMBER:-0}"

if [[ -z "${PR_NUMBER}" ]] || [[ "${PR_NUMBER}" == "0" ]]; then
  echo "No pull request context detected. Writing to step summary."
  echo "${COMMENT_BODY}" >> "${GITHUB_STEP_SUMMARY}"
  echo "Review written to GITHUB_STEP_SUMMARY."
  exit 0
fi

# ---------------------------------------------------------------
# Search for an existing comment with the marker
# ---------------------------------------------------------------
echo "Searching for existing review comment on PR #${PR_NUMBER}..."

EXISTING_COMMENT_ID=$(
  gh api \
    "repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
    --paginate \
    --jq '.[] | select(.body | contains("<!-- yeah-action-dependency-review -->")) | .id' \
  | head -1 || true
)

# ---------------------------------------------------------------
# Prepare the JSON payload via jq (handles special characters)
# ---------------------------------------------------------------
PAYLOAD_FILE=$(mktemp /tmp/yeah-action-payload-XXXXXX.json)
jq -n --arg body "${COMMENT_BODY}" '{"body": $body}' > "${PAYLOAD_FILE}"

# ---------------------------------------------------------------
# Post or update the comment
# ---------------------------------------------------------------
if [[ -n "${EXISTING_COMMENT_ID}" ]]; then
  echo "Updating existing comment (ID: ${EXISTING_COMMENT_ID})..."
  gh api \
    --method PATCH \
    "repos/${GITHUB_REPOSITORY}/issues/comments/${EXISTING_COMMENT_ID}" \
    --input "${PAYLOAD_FILE}"
  echo "Comment updated."
else
  echo "Creating new comment on PR #${PR_NUMBER}..."
  gh api \
    --method POST \
    "repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
    --input "${PAYLOAD_FILE}"
  echo "Comment created."
fi

# Clean up
rm -f "${PAYLOAD_FILE}"

echo "PR comment posted successfully."
