#!/usr/bin/env python3
"""
post_comment.py

Posts or updates a sticky PR comment with the dependency security review.
Falls back to GITHUB_STEP_SUMMARY when no PR context is available.
"""

import json
import os
import subprocess
import sys
import tempfile


def _gh_api(*args):
    """Run a gh api command and return (stdout, returncode)."""
    result = subprocess.run(
        ["gh", "api", *args],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout.strip(), result.returncode


def main():
    # Validate required environment variables.
    for var in ("GH_TOKEN", "REVIEW_FILE"):
        if not os.environ.get(var):
            print(f"Error: {var} must be set", file=sys.stderr)
            sys.exit(1)

    review_file = os.environ["REVIEW_FILE"]
    ecosystem = os.environ.get("ECOSYSTEM", "unknown")
    dependencies = os.environ.get("DEPENDENCIES", "none")
    github_repo = os.environ.get("GITHUB_REPOSITORY", "")
    step_summary = os.environ.get("GITHUB_STEP_SUMMARY", os.devnull)
    action_repo = os.environ.get("GITHUB_ACTION_REPOSITORY",
                                 "lklimek/yeah-action")
    pr_number = os.environ.get("PR_NUMBER", "0") or "0"

    if not github_repo:
        print("Error: GITHUB_REPOSITORY must be set", file=sys.stderr)
        sys.exit(1)

    # Read review content.
    if not os.path.isfile(review_file):
        print(f"Error: Review file not found at {review_file}",
              file=sys.stderr)
        sys.exit(1)

    with open(review_file) as f:
        review_content = f.read()

    # Build the comment body.
    marker = "<!-- yeah-action-dependency-review -->"
    comment_body = (
        f"{marker}\n"
        f"## Dependency Security Review\n\n"
        f"| Field | Value |\n"
        f"|-------|-------|\n"
        f"| **Ecosystem** | {ecosystem} |\n"
        f"| **Dependencies** | {dependencies} |\n\n"
        f"---\n\n"
        f"{review_content}\n\n"
        f"---\n"
        f"<sub>Generated by [yeah-action](https://github.com/{action_repo}) "
        f"dependency security review</sub>"
    )

    # Truncate if needed (GitHub limit: 65535 chars).
    max_length = 65000
    if len(comment_body) > max_length:
        print(f"Warning: Comment body exceeds {max_length} characters; "
              "truncating.")
        comment_body = comment_body[:max_length] + "\n\n... (truncated)"

    # If there is no PR, write to step summary instead.
    if pr_number == "0":
        print("No pull request context detected. Writing to step summary.")
        with open(step_summary, "a") as f:
            f.write(comment_body)
            f.write("\n")
        print("Review written to GITHUB_STEP_SUMMARY.")
        return

    # Search for an existing comment with the marker.
    print(f"Searching for existing review comment on PR #{pr_number}...")
    out, _ = _gh_api(
        f"repos/{github_repo}/issues/{pr_number}/comments",
        "--paginate",
        "--jq",
        '.[] | select(.body | contains("<!-- yeah-action-dependency-review -->")) | .id',
    )
    existing_id = out.splitlines()[0] if out.strip() else ""

    # Prepare the JSON payload.
    fd, payload_file = tempfile.mkstemp(
        prefix="yeah-action-payload-", suffix=".json"
    )
    with os.fdopen(fd, "w") as f:
        json.dump({"body": comment_body}, f)

    try:
        if existing_id:
            print(f"Updating existing comment (ID: {existing_id})...")
            _gh_api(
                "--method", "PATCH",
                f"repos/{github_repo}/issues/comments/{existing_id}",
                "--input", payload_file,
            )
            print("Comment updated.")
        else:
            print(f"Creating new comment on PR #{pr_number}...")
            _gh_api(
                "--method", "POST",
                f"repos/{github_repo}/issues/{pr_number}/comments",
                "--input", payload_file,
            )
            print("Comment created.")
    finally:
        os.unlink(payload_file)

    print("PR comment posted successfully.")


if __name__ == "__main__":
    main()
